name: user_repository
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  grpc: ^3.0.2
  users_service:
    git:
      url: https://github.com/fdl-mc/stubs
      path: dart/users_service
