name: freedomland

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  go_router: ^5.0.5

  user_repository:
    path: ./packages/user-repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true