name: freedomland

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  user_repository:
    path: ./packages/user-repository
  economy_repository:
    path: ./packages/economy-repository
  auth_repository:
    path: ./packages/auth-repository

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  go_router: ^5.0.5
  equatable: ^2.0.5
  meta: ^1.8.0
  formz: ^0.4.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true