name: fdl_app
description: FreedomLand ecosystem app.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    adaptive_theme: ^2.3.0
    flutter_riverpod: ^0.14.0+3
    routemaster: ^0.9.5
    firebase_core: ^1.8.0
    firebase_auth: ^3.1.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
    fonts:
        - family: CustomIcons
          fonts:
              - asset: assets/fonts/CustomIcons.ttf
